version: '3.8'

services:
  # Milvus Standalone 服務
  milvus:
    image: milvusdb/milvus:v2.3.3
    container_name: podwise_milvus_standalone
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_USE_EMBED: "true"
      ETCD_DATA_DIR: "/var/lib/milvus/etcd"
      ETCD_CONFIG_PATH: "/milvus/configs/etcd.yaml"
      MINIO_ADDRESS: "minio:9000"
      MINIO_ACCESS_KEY: "bdse37"
      MINIO_SECRET_KEY: "11111111"
    ports:
      - "19530:19530" # Milvus 服務埠
      - "9091:9091" # 健康檢查埠
    volumes:
      - milvus_data:/var/lib/milvus
    networks:
      - milvus_network
    depends_on:
      - minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO 物件儲存（Milvus 需要）
  minio:
    image: minio/minio:latest
    container_name: podwise_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: bdse37
      MINIO_ROOT_PASSWORD: 11111111
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    volumes:
      - minio_data:/data
    networks:
      - milvus_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  milvus_data:
    driver: local
  minio_data:
    driver: local

networks:
  milvus_network:
    driver: bridge
