apiVersion: batch/v1
kind: Job
metadata:
  name: episode-processor-job
  namespace: podwise
spec:
  template:
    metadata:
      name: episode-processor
    spec:
      containers:
      - name: episode-processor
        image: python:3.10-slim
        command: ["/bin/bash"]
        args:
        - -c
        - |
          # 安裝依賴
          pip install psycopg2-binary
          
          # 複製處理腳本到容器
          cat > episode_processor.py << 'EOF'
          # 這裡會插入完整的 episode_processor.py 內容
          EOF
          
          cat > config.py << 'EOF'
          # 這裡會插入完整的 config.py 內容
          EOF
          
          # 執行處理腳本
          python episode_processor.py --episodes-dir /episodes --insert-db --verbose
        volumeMounts:
        - name: episodes-data
          mountPath: /episodes
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "podcast"
        - name: POSTGRES_USER
          value: "bdse37"
        - name: POSTGRES_PASSWORD
          value: "111111"
        - name: K8S_NAMESPACE
          value: "podwise"
      volumes:
      - name: episodes-data
        hostPath:
          path: /home/bai/Desktop/Podwise/backend/postgresql_cleanup/episodes
          type: Directory
      restartPolicy: Never
  backoffLimit: 3 