# STT 服務持久化儲存配置
# 用於儲存語音識別模型檔案和音訊快取

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stt-models-pvc
  namespace: podwise
  labels:
    app: stt
    component: models
  annotations:
    description: "STT 語音識別模型檔案持久化儲存"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stt-cache-pvc
  namespace: podwise
  labels:
    app: stt
    component: cache
  annotations:
    description: "STT 音訊快取持久化儲存"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stt-audio-pvc
  namespace: podwise
  labels:
    app: stt
    component: audio
  annotations:
    description: "STT 音訊檔案持久化儲存"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # 音訊檔案儲存
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stt-output-pvc
  namespace: podwise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client 