apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-service
  namespace: podwise
  labels:
    app: ollama-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-service
  template:
    metadata:
      labels:
        app: ollama-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1  # 部署到 worker1 節點
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        - name: OLLAMA_ORIGINS
          value: "*"
        resources:
          requests:
            memory: "8Gi"
            cpu: "4"
          limits:
            memory: "100Gi"
            cpu: "16"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: podwise
spec:
  selector:
    app: ollama-service
  ports:
  - port: 11434
    targetPort: 11434
    nodePort: 31134
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: podwise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path 