apiVersion: v1
kind: Service
metadata:
  name: ollama-nodeport
  namespace: podwise
spec:
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434
    nodePort: 31134
  type: NodePort 