# 層級化 RAG Pipeline 配置檔案

# 層級化結構配置
hierarchical_structure:
  # 第一層：查詢處理
  level_1_query_processing:
    name: "查詢重寫轉換拓展"
    confidence_threshold: 0.7
    fallback_strategy: "level2"

  # 第二層：混合搜尋
  level_2_hybrid_search:
    name: "混合搜尋"
    confidence_threshold: 0.6
    fallback_strategy: "level3"
    search_methods:
      - "dense"
      - "sparse"
      - "semantic"
    fusion_weights:
      dense: 0.4
      sparse: 0.3
      semantic: 0.3

  # 第三層：檢索增強
  level_3_retrieval_augmentation:
    name: "檢索增強"
    confidence_threshold: 0.5
    fallback_strategy: "level4"
    augmentation_methods:
      - "context_expansion"
      - "knowledge_graph"
      - "external_data"

  # 第四層：重新排序
  level_4_reranking:
    name: "重新排序"
    confidence_threshold: 0.6
    fallback_strategy: "level5"
    ranking_criteria:
      - "relevance"
      - "diversity"
      - "personalization"

  # 第五層：上下文壓縮
  level_5_context_compression:
    name: "上下文壓縮"
    confidence_threshold: 0.5
    fallback_strategy: "level6"
    compression_ratio: 0.7
    max_tokens: 1000

  # 第六層：混合式 RAG
  level_6_hybrid_rag:
    name: "混合式 RAG"
    confidence_threshold: 0.4
    fallback_strategy: "fallback_service"
    generation_methods:
      - "multi_model"
      - "adaptive"
      - "quality_control"

# 通用設定
general:
  max_retries: 3
  timeout: 30
  log_level: "INFO"
  enable_monitoring: true
  enable_caching: true
  cache_ttl: 3600

# 模型設定
models:
  llm_endpoint: "http://llm-service:8000"
  embedding_endpoint: "http://llm-service:8000/embeddings"
  vector_store: "milvus"
  milvus_host: "192.168.32.86"  # worker3 IP (Docker container)
  milvus_port: 19530

# 資料處理設定
data_processing:
  chunk_size: 1000
  chunk_overlap: 200
  max_chunks: 10
  min_chunk_size: 100 