apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: minio
  namespaceSelector:
    matchNames:
      - podwise
  endpoints:
    - port: api
      path: /minio/v2/metrics/cluster
      interval: 30s
