apiVersion: v1
kind: Secret
metadata:
  name: openai-secrets
  namespace: podwise
  labels:
    app: rag-pipeline-service
type: Opaque
data:
  # 請將您的 OpenAI API Key 進行 base64 編碼後填入
  # echo -n "your_openai_api_key_here" | base64
  OPENAI_API_KEY: ""  # 請填入 base64 編碼後的 API Key
---
# 如果沒有 OpenAI API Key，可以創建一個空的 secret
apiVersion: v1
kind: Secret
metadata:
  name: openai-secrets-empty
  namespace: podwise
  labels:
    app: rag-pipeline-service
type: Opaque
data:
  OPENAI_API_KEY: ""  # 空值，表示不使用 OpenAI 備援 