# RAG Pipeline 單節點部署 PVC 配置
# 簡化的持久化儲存配置

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-data-pvc
  namespace: podwise
  labels:
    app: rag-pipeline
    component: data
  annotations:
    description: "RAG Pipeline 資料持久化儲存"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # 資料儲存
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-models-pvc
  namespace: podwise
  labels:
    app: rag-pipeline
    component: models
  annotations:
    description: "RAG Pipeline 模型檔案持久化儲存"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi  # 模型檔案
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-cache-pvc
  namespace: podwise
  labels:
    app: rag-pipeline
    component: cache
  annotations:
    description: "RAG Pipeline 快取檔案持久化儲存"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # 快取檔案
  storageClassName: nfs-client 