apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicgen-service
  namespace: podwise
  labels:
    app: musicgen-service
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicgen-service
  template:
    metadata:
      labels:
        app: musicgen-service
        version: v1.0.0
    spec:
      containers:
      - name: musicgen
        image: 192.168.32.38:5000/musicgen-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8005
          name: http
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: PYTHONPATH
          value: "/app"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
          limits:
            memory: "32Gi"
            cpu: "8"
        volumeMounts:
        - name: musicgen-cache
          mountPath: /app/cache
        - name: musicgen-output
          mountPath: /app/output
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: musicgen-cache
        persistentVolumeClaim:
          claimName: musicgen-cache-pvc
      - name: musicgen-output
        persistentVolumeClaim:
          claimName: musicgen-output-pvc
      nodeSelector:
        kubernetes.io/hostname: "worker2"
---
apiVersion: v1
kind: Service
metadata:
  name: musicgen-service
  namespace: podwise
  labels:
    app: musicgen-service
spec:
  type: ClusterIP
  ports:
  - port: 8005
    targetPort: 8005
    protocol: TCP
    name: http
  selector:
    app: musicgen-service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicgen-cache-pvc
  namespace: podwise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicgen-output-pvc
  namespace: podwise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client 