apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: podwise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Gi
  storageClassName: nfs-client
  volumeName: podwise-postgres-pvc-pvc-bf12702a-9716-412c-bb80-5387720e61fa
