# config/config.yaml
app:
  name: "Podri TTS"
  version: "1.0.0"
  description: "台灣在地化 TTS 語音合成系統"

tts:
  default_voice: "zh-TW-HsiaoChenNeural"
  default_rate: 1.0
  default_pitch: 0
  default_style: "friendly"
  
  # 支援的語音列表
  voices:
    - id: "hsiao_chen"
      name: "曉臻"
      voice_id: "zh-TW-HsiaoChenNeural"
      language: "zh-TW"
      gender: "Female"
      styles: ["friendly", "cheerful", "empathetic"]
      
    - id: "yun_jhe"
      name: "雲哲"
      voice_id: "zh-TW-YunJheNeural"
      language: "zh-TW"
      gender: "Male"
      styles: ["general", "serious"]
      
    - id: "hsiao_yu"
      name: "曉雨"
      voice_id: "zh-TW-HsiaoYuNeural"
      language: "zh-TW"
      gender: "Female"
      styles: ["cheerful", "sad", "excited"]

audio:
  sample_rate: 24000
  channels: 1
  format: "mp3"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
