apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secrets
  namespace: podwise
type: Opaque
stringData:
  LANGFUSE_PUBLIC_KEY: "pk-lf-c1687e6b-9bb9-4361-bb48-fe3feded144a"
  LANGFUSE_SECRET_KEY: "sk-lf-84371141-e312-4c32-b46a-c90ebdb479fe"
  LANGFUSE_HOST: "https://cloud.langfuse.com"
